# cloudrun-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-pipeline # Name of your Cloud Run service, based on your input
  annotations:
    run.googleapis.com/ingress: all # THIS MAKES THE SERVICE PUBLICLY ACCESSIBLE
    run.googleapis.com/client-name: cloud-deploy # Indicates deployment by Cloud Deploy
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0" # Allows scaling down to zero instances
    spec:
      containers:
      - image: gcr.io/pr-db-fn-1/temp-convert-webapp@sha256:419a8e44f74f475893007c3991be20cc0dc6b22eb5cab12477f16ba70a5d8a69 # Your specified container image
        ports:
        - containerPort: 5000 # Your specified port
      serviceAccountName: terraform-service-account-2@pr-db-fn-1.iam.gserviceaccount.com # Use 'default' or a specific service account with Cloud Run Admin role